[versions]
gradle-binary-compat = "0.13.2"
gradle-kmp-configuration = "0.1.7"
gradle-kotlin = "1.9.21"
gradle-publish-maven = "0.25.3"

immutable = "0.1.0"

kmp-file = "0.1.0-alpha06"
kmp-tor-resource = "408.10.0-SNAPSHOT"
kotlinx-coroutines = "1.7.3"

[libraries]
gradle-kmp-configuration = { module = "io.matthewnelson:gradle-kmp-configuration-plugin", version.ref = "gradle-kmp-configuration" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "gradle-kotlin" }
gradle-publish-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradle-publish-maven" }

immutable-collections = { module = "io.matthewnelson.immutable:collections", version.ref = "immutable" }

kmp-file = { module = "io.matthewnelson.kmp-file:file", version.ref = "kmp-file" }
kmp-tor-resource-tor = { module = "io.matthewnelson.kmp-tor:resource-tor", version.ref = "kmp-tor-resource" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

[plugins]
binary-compat = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "gradle-binary-compat" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "gradle-kotlin" }
